# Generated by Django 5.2.5 on 2025-09-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='acceso_modulos',
            new_name='carpetas',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='formularios',
            field=models.JSONField(default=list),
        ),
    ]
