# Generated by Django 5.2.5 on 2025-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_acceso_modulos_perfilusuario_carpetas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='carpetas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='formularios',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_estructura',
            field=models.JSONField(default=dict),
        ),
    ]
